# 项目相关配置
rock-blade:
  # 文件路径 示例（ Windows配置W:/WorkSpace/java/uploadPath，Linux配置 /home/baseFramework/uploadPath）
  profile: ${PROFILE_PATH}
  jwt:
    #白名单
    white-list: /profile/**,/doc.html,/webjars/**,/favicon.ico,/v3/api-docs/**,/swagger-ui.html,/swagger-ui/**,/auth/*

# DataSource Config
spring:
  datasource:
      url: ${DEV_DATABASE_URL}
      username: ${DEV_DATABASE_USERNAME}
      password: ${DEV_DATABASE_PASSWORD}    
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT:6379}
      password: ${DEV_REDIS_PASSWORD}
      database: ${DEV_REDIS_DATABASE:0}
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  # 邮件服务配置
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true         

sa-token:               
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET_KEY}

server:
  port: 8080
  servlet:
    context-path: /rock-blade

#Mybatis-Flex
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "系统后台"
      paths-to-match: "/**"
      packages-to-scan: com.rockblade.interfaces.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
