name: Continuous Integration

on:
  push:
    branches: [ master, develop, feature/CI-CD ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Check Code Style
        run: ./mvnw spotless:check
      
      - name: Run Tests & Coverage
        run: ./mvnw verify
      
      - name: Build Package
        run: ./mvnw package -DskipTests
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: target/*.jar