name: Continuous Integration

on:
  push:
    branches: [ master, develop, release/* ]
  pull_request:
    branches: [ master, develop, release/* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Check Code Style
        run: ./mvnw spotless:check
      
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Run Tests & Coverage
        run: ./mvnw verify
      
      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw sonar:sonar \
          -Dsonar.projectKey=rock-blade-java \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      
      - name: Build Package
        run: ./mvnw package -DskipTests
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: target/*.jar